[general]
# https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[window]
dimensions.columns = 80
dimensions.lines = 24
padding.x = 3
padding.y = 3
dynamic_padding = true
opacity = 0.95

[font]
size = 12
normal.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", mods = "Control", action = "Paste" }
]

