# Generals
profile=gpu-hq
gpu-api=opengl
deband=no

# Video
scale=spline16
dscale=spline16
cscale=sinc
cscale-window=blackman
cscale-radius=3

# Audio
alang=ja,jp,jpn,en,eng
slang=en,eng,vie,vi,vn

# Subtitle
demuxer-mkv-subtitle-preroll=yes
sub-ass-vsfilter-blur-compat=yes
sub-fix-timing=yes
sub-gauss=1.0
sub-gray=yes
sub-font-size=42
sub-border-color=0.0/0.0/0.0/1.0
sub-border-size=2.0
sub-use-margins=no
sub-shadow-color=0.0/0.0/0.0/0.5
sub-shadow-offset=2

# Screenshots
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=5
screenshot-jpeg-quality=95
screenshot-directory="~/Pictures/mpv"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

[1080p]
# profile-desc=cond:string.match(p.filename, "1080")~=nil
profile-desc=cond:((p["video-params/h"] >= 720))
scale=bicubic_fast
dscale=bicubic_fast
cscale=bicubic_fast

[extension.gif]
loop-file=inf
